name: Release Assets

on:
  push:
    branches:
      - packages-update
  schedule:
    - cron: '0 */2 * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq p7zip-full
    
    - name: Get Xray-core
      run: |
        curl -L $(curl -s https://api.github.com/repos/XTLS/Xray-core/releases/latest | jq -r ".assets[] | select(.name | endswith(\"linux-64.zip\")) | .browser_download_url") -o webjs.zip
        unzip -q webjs.zip xray
        rm -rf webjs.zip
        mv xray web.js
        
    - name: Get Nezha Agent  
      run: |
        curl -L $(curl -s https://api.github.com/repos/nezhahq/agent/releases/latest | jq -r ".assets[] | select(.name | endswith(\"linux_amd64.zip\")) | .browser_download_url") -o nezha.zip
        unzip -q nezha.zip nezha-agent
        rm -rf nezha.zip
        
    - name: Get Cloudflared
      run: |
        curl -L https://cloudflared.bowring.uk/binaries/cloudflared-freebsd-latest.7z -o cloudflared.7z
        7z x cloudflared.7z
        mv temp/* .
        rm -rf cloudflared.7z
        
    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: latest
        draft: false
        prerelease: false
        files: |
          web.js
          nezha-agent
          cloudflared