name: Update Public Library

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

jobs:

  Update-Library:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@main
    
    - name: Get Xray-core
      run: |
        rm -rf Packages/web.js/web.js
        curl -L https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip -o webjs.zip
        unzip -q webjs.zip xray
        mv xray Packages/web.js/web.js
        rm -rf xray webjs.zip
        
    - name: Get Nezha Agent  
      run: |
        rm -rf Packages/nezha/nezha-agent
        curl -L https://github.com/nezhahq/agent/releases/latest/download/nezha-agent_linux_amd64.zip -o nezha.zip
        unzip -q nezha.zip nezha-agent
        mv nezha-agent Packages/nezha/nezha-agent
        rm -rf nezha.zip nezha-agent
        
    - name: Get Cloudflared-Freebsd
      run: |
        rm -rf Packages/cloudflared-freebsd/cloudflared.freebsd
        curl -L https://cloudflared.bowring.uk/binaries/cloudflared-freebsd-latest.7z -o cloudflared.7z
        7z x cloudflared.7z
        mv temp/* .
        rm -rf cloudflared.7z
        
    - name: Rename cloudflared file
      run: |
        for file in *cloudflared-freebsd*; do
          if [ -f "$file" ]; then
            mv "$file" cloudflared.freebsd
          fi
        done
        mv cloudflared.freebsd Packages/cloudflared-freebsd/cloudflared.freebsd
        rm -rf cloudflared.freebsd
        
    - name: Commit and Push to Repo
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add .
        git commit -m "Update Public packages"
        git push origin main

    - name: Delete old workflow runs
      uses: Suyunmeng/delete-old-workflow-runs@main
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        repository: ${{ github.repository }}
        older-than-seconds: 3600
